### ISSUE TITLE
TextBlocks updating incorrectly

### ISSUE THREAD

**Issue by matthewcrews** [fsprojects/Avalonia.FuncUI#369] opened 2023-11-10 02:16 UTC
I am having trouble with an app for work. I tried to create a minimal example, but it didn't reproduce the bug.

I have a list of `TextBlock` with `onPointerSelected` handlers.

```fsharp
for KeyValue (experimentId, experiment) in state.Model.Experiments do
    TextBlock.create [
        TextBlock.text experiment.Name
        TextBlock.onPointerPressed (fun e ->
            e.Handled <- true
            dispatch (Msg.SelectionChanged (NewSelection.Experiment experimentId)))
    ]
```

The `Experiments` fields that is being iterated through is a `Map<int, Experiment>`.

```fsharp
type Experiment =
    {
        Id: ExperimentId
        Seed: string
        TimeUnit: TimeUnit
        Duration: string
        Iterations: string
        Name: string
        SinkBuffers: string
        TheoreticalLimit: string
    }
```

When I click on the `TextBlock`, a `Msg` is dispatched that's supposed to update a selection. What's happening, though is that the text in the fields is getting swapped around. You will notice in this GIF how the first entry keeps having the number change. This should not be happening. I tried using the `View.createWithKey` trick to force a re-render, but that doesn't help.

![2023-11-09_18-14-03](https://github.com/fsprojects/Avalonia.FuncUI/assets/1593215/e5118224-1474-497e-9519-8ea4eb7a436e)

I'm sorry for the lack of a fully reproduced example. This is an internal app and I can't share the source code. I tried reproducing a small example, but it didn't have the same bug.

**Comment by JaggerJo** [comment] 2023-11-10 08:21
Hey @matthewcrews 👋

I see 2 problems:

1. Iterating over the map `Map<int, Experiment>` will not return items in a stable order. Sort them by some stable value before rendering or items might change/swap places.

2. When items change places the backing controls might be reuses (if the type matches and no key it set that changes)

FuncUI has no idea if the `onPointerPressed` function changed. (if views swap places, it did) 
You can give FuncUI the necessary context, by passing `SubPatchOptions` 

<img width="1352" alt="image" src="https://github.com/fsprojects/Avalonia.FuncUI/assets/13090415/32ee6d33-489a-43c3-9e5c-db2b58d3ae03">

<img width="1352" alt="image" src="https://github.com/fsprojects/Avalonia.FuncUI/assets/13090415/46639b42-96e9-4d45-a8c9-56a59f8db163">

**Comment by matthewcrews** [comment] 2023-11-10 15:07
@JaggerJo I'm actually fairly certain that a `Map` returns the elements in ascending order of the keys. Also, I was originally using a `ResizeArray` as the backing collection and I had the exact same issue.

I have the same problem with the UI when I change the code to this:
```fsharp
let orderedItems = state.Model.Experiments |> Seq.sortBy (fun (KeyValue(k, _)) -> k)
for KeyValue (experimentId, experiment) in orderedItems do
    TextBlock.create [
        TextBlock.text experiment.Name
        TextBlock.onPointerPressed ((fun e ->
            e.Handled <- true
            dispatch (Msg.SelectionChanged (NewSelection.Experiment experimentId)))
            , SubPatchOptions.Always)
    ]
```

**Comment by JaggerJo** [comment] 2023-11-10 15:17
Could you provide me with a stripped app so I can reproduce it locally?

**Comment by matthewcrews** [comment] 2023-11-10 15:42
I will try. I did try initially but a simple example did not reproduce the bug. I will try to take the original app and strip out the proprietary code.

**Comment by matthewcrews** [comment] 2023-11-10 20:47
Here is a repo that reproduces the bug:
https://github.com/matthewcrews/ConfusingTextBox

Run the app, go to the `Experiment` sheet by clicking on the icon that looks like chemistry beakers:
![image](https://github.com/fsprojects/Avalonia.FuncUI/assets/1593215/d33d38f9-93e8-4734-ae8b-c0a76876b128)

Add several Experiments by clicking on `+` button, and try clicking the different text boxes.
![image](https://github.com/fsprojects/Avalonia.FuncUI/assets/1593215/78dce562-b890-417a-8c09-88c4ea925633)

You'll see that the first experiment you click on will have the displayed name constantly change as you click between them.

**Comment by JaggerJo** [comment] 2023-11-11 13:22
@matthewcrews I've looked at your code and I know why it happens. Also I know you don't want to hear it but the component model is great and helps with things like this 😉.

-------

So.. you have a list of experiments on the left. You render details of the selected experiment details on the right. 

The problem is that the **details view is not keyed**, so FuncUI will patch it. By patching it (e.g. setting `TextBox.text` to the selected experiments name) the already existing handler `TextBox.onTextChanged` will fire. This handler does not have `SubPatchOptions` set, so it will never change. The first experiment you click on will set all the handlers - because the handlers close over state.

→ Use keyed views when you switch the views context. (otherwise you need to be careful with your handlers closing over state)

**Comment by JaggerJo** [comment] 2023-11-11 13:23
Adding a key here fixes the issue described above:

<img width="816" alt="Screenshot 2023-11-11 at 14 22 44" src="https://github.com/fsprojects/Avalonia.FuncUI/assets/13090415/1986e1c8-3228-4d51-924f-c9d0891878e7">

**Comment by matthewcrews** [comment] 2023-11-13 03:50
I am confirming this resolves the issue.

**Closed** 2024-02-03 23:03 UTC
